
server:
  port: 8082


# Feign Client
feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution.isolation.thread.timeoutInMilliseconds: 610
  
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        input:
          group: vodplay
          destination: team3vod
          contentType: application/json
        output:
          destination: team3vod
          contentType: application/json
